### ISSUE TITLE
Initialize DreamYaml with InputStream

### ISSUE THREAD

**Issue by Rubenicos** [Osiris-Team/Dream-Yaml#7]
Example:
```java
ClassLoader classLoader = getClass().getClassLoader();

DreamYaml yaml = new DreamYaml(classLoader.getResourceAsStream("somePath/yamlStuff.yml"));
```

With a little change on DYReader:
```java
public void parse(DreamYaml yaml) {
    ...
    if (yaml.getFile() != null) {
        // Some stuff if file path is present
        ...
        reader = new BufferedReader(new FileReader(file));
    } else {
        // Use InputStream instead
        reader = new BufferedReader(new InputStreamReader(yaml.getStream()));
    }
}
```

**Comment by Osiris-Team** [comment]
@Rubenicos Yep I like the idea.

**Comment by Osiris-Team** [comment]
@Rubenicos I'm currently working on other stuff though, that's why I'll be able to implement this only in a few weeks I guess.
You could implement it by yourself maybe?

**Comment by Rubenicos** [comment]
> @Rubenicos I'm currently working on other stuff though, that's why I'll be able to implement this only in a few weeks I guess.
> You could implement it by yourself maybe?

Sure
